
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/profixer/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npm run build
    - cp -R $DEPLOYPATH/dist/* $DEPLOYPATH/
    - cat > $DEPLOYPATH/.htaccess << 'EOL'
# Activare rewrite engine
RewriteEngine On
RewriteBase /

# Setarea MIME type-urilor pentru JavaScript
<IfModule mod_mime.c>
  AddType text/javascript .js .mjs .jsx
</IfModule>

# Redirectare pentru SPA
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
EOL
