
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/profixer/public_html
    # Curățăm directorul de destinație înainte de a copia noile fișiere
    - /bin/rm -rf $DEPLOYPATH/*
    # Executăm build local
    - /usr/local/cpanel/3rdparty/bin/node /usr/local/cpanel/3rdparty/bin/npm install
    - /usr/local/cpanel/3rdparty/bin/node /usr/local/cpanel/3rdparty/bin/npm run build
    # Copiem conținutul folderului dist în directorul public_html
    - /bin/cp -R dist/* $DEPLOYPATH/
    # Creare fișier .htaccess în directorul de destinație
    - /bin/cat > $DEPLOYPATH/.htaccess << 'EOL'
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-l
  RewriteRule . /index.html [L]
</IfModule>

# Setarea MIME type-urilor pentru JavaScript
AddType text/javascript .js
AddType text/javascript .mjs
AddType application/json .json
EOL
