
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/profixer/public_html
    # Build local înainte de deployment
    - npm install
    - npm run build
    # Copiere doar a fișierelor din dist direct în directorul de bază
    - /bin/cp -R dist/* $DEPLOYPATH/
    # Crearea unui .htaccess personalizat în directorul de destinație
    - cat > $DEPLOYPATH/.htaccess << 'EOL'
# Activare rewrite engine
RewriteEngine On
RewriteBase /

# Setarea MIME type-urilor pentru JavaScript
<IfModule mod_mime.c>
  AddType text/javascript .js .mjs
</IfModule>

# Redirectare pentru SPA
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
EOL
