
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/profixer/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npm run build
    - cp -R $DEPLOYPATH/dist/* $DEPLOYPATH/
