
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acmknwxnyibvbbltfdxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbWtud3hueWlidmJibHRmZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczOTc2NDIsImV4cCI6MjA1Mjk3MzY0Mn0.StIEGX1joj7gESXTn5jdtFNvDBMmvDKILchNr_BYUHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    fetch: (...args: Parameters<typeof fetch>) => fetch(...args)
  }
});
